/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'weeklyGoal' : IDL.Nat,
  'totalSessionsCompleted' : IDL.Nat,
  'lastSessionDate' : IDL.Int,
  'weeklySessionCount' : IDL.Nat,
  'streakCount' : IDL.Nat,
});
export const Difficulty = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const TargetArea = IDL.Variant({
  'eyes' : IDL.Null,
  'neck' : IDL.Null,
  'fullFace' : IDL.Null,
  'cheeks' : IDL.Null,
  'jawline' : IDL.Null,
  'forehead' : IDL.Null,
});
export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'difficulty' : Difficulty,
  'name' : IDL.Text,
  'tips' : IDL.Text,
  'description' : IDL.Text,
  'instructions' : IDL.Vec(IDL.Text),
  'targetArea' : TargetArea,
});
export const Session = IDL.Record({
  'completedAt' : IDL.Int,
  'exerciseIds' : IDL.Vec(IDL.Nat),
  'durationSeconds' : IDL.Nat,
  'sessionId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getExercisesByArea' : IDL.Func([TargetArea], [IDL.Vec(Exercise)], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getSessionHistory' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileOrCreate' : IDL.Func([], [UserProfile], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordSession' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Nat], [IDL.Int], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleFavorite' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'weeklyGoal' : IDL.Nat,
    'totalSessionsCompleted' : IDL.Nat,
    'lastSessionDate' : IDL.Int,
    'weeklySessionCount' : IDL.Nat,
    'streakCount' : IDL.Nat,
  });
  const Difficulty = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const TargetArea = IDL.Variant({
    'eyes' : IDL.Null,
    'neck' : IDL.Null,
    'fullFace' : IDL.Null,
    'cheeks' : IDL.Null,
    'jawline' : IDL.Null,
    'forehead' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'difficulty' : Difficulty,
    'name' : IDL.Text,
    'tips' : IDL.Text,
    'description' : IDL.Text,
    'instructions' : IDL.Vec(IDL.Text),
    'targetArea' : TargetArea,
  });
  const Session = IDL.Record({
    'completedAt' : IDL.Int,
    'exerciseIds' : IDL.Vec(IDL.Nat),
    'durationSeconds' : IDL.Nat,
    'sessionId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getExercisesByArea' : IDL.Func(
        [TargetArea],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getSessionHistory' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileOrCreate' : IDL.Func([], [UserProfile], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordSession' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Nat], [IDL.Int], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleFavorite' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };