/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Difficulty = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface Exercise {
  'id' : bigint,
  'duration' : bigint,
  'difficulty' : Difficulty,
  'name' : string,
  'tips' : string,
  'description' : string,
  'instructions' : Array<string>,
  'targetArea' : TargetArea,
}
export interface Session {
  'completedAt' : bigint,
  'exerciseIds' : Array<bigint>,
  'durationSeconds' : bigint,
  'sessionId' : bigint,
}
export type TargetArea = { 'eyes' : null } |
  { 'neck' : null } |
  { 'fullFace' : null } |
  { 'cheeks' : null } |
  { 'jawline' : null } |
  { 'forehead' : null };
export interface UserProfile {
  'weeklyGoal' : bigint,
  'totalSessionsCompleted' : bigint,
  'lastSessionDate' : bigint,
  'weeklySessionCount' : bigint,
  'streakCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExercises' : ActorMethod<[], Array<Exercise>>,
  'getExercisesByArea' : ActorMethod<[TargetArea], Array<Exercise>>,
  'getFavorites' : ActorMethod<[], Array<bigint>>,
  'getSessionHistory' : ActorMethod<[], Array<Session>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileOrCreate' : ActorMethod<[], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordSession' : ActorMethod<[Array<bigint>, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleFavorite' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];